### ISSUE TITLE
use strict: command not found

### ISSUE THREAD

**Issue by davorpeic** [hypery2k/nativescript-media-generator#14]
Hi,

Testing 0.2.4 Don't hate me :)

1. So, now I get this issue `use strict: command not found`, and adding `#!/usr/bin/env node` at the first line of `tns-media-gen.js` fixes that issue. Credits: http://stackoverflow.com/questions/34353512/node-npm-package-throw-use-strict-command-not-found-after-publish-and-install-g

2. After that, it looks like there has to be `mediagen-config.json` in the root, because without it I get 
```
Cannot find module '/Users/MyFolder/app/mediagen-config'
```

So I create simple config (must have json in it, if not this error is dropped `SyntaxError: /Users/myapps.../mediagen-config.json: Unexpected end of JSON input`
```
{
    "icon": {
        "filename": "icon2.png",
        "background": "323232"
    },
    "splash": {
        "filename": "splash.png",
        "background": "323232"
    }    
}
```

Then running `tns-media-gen` start to generate assets, the only few errors are related with android, not sure why, ios gets generated fine, these are all the errors I have, I hope it helps track the issue

```
------------------------------
   nativescript-media-generator
------------------------------
Generating 42 images so you don't have to
------------------------------
Write file error { Error: Command failed: convert: invalid argument for option '-extent': /Users/MyUser/MyApp/app/App_Resources/Android/drawable-mdpi/splash.png @ error/convert.c/ConvertImageCommand/1542.

    at ChildProcess.onExit (/Users/MyUser/.nvm/v6.7.0/lib/node_modules/nativescript-media-generator/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12) code: 1, signal: null }
Write file error { Error: Command failed: convert: invalid argument for option '-extent': /Users/MyUser/MyApp/app/App_Resources/Android/drawable-hdpi/splash.png @ error/convert.c/ConvertImageCommand/1542.

    at ChildProcess.onExit (/Users/MyUser/.nvm/v6.7.0/lib/node_modules/nativescript-media-generator/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12) code: 1, signal: null }
Write file error { Error: Command failed: convert: invalid argument for option '-extent': /Users/MyUser/MyApp/app/App_Resources/Android/drawable-xhdpi/splash.png @ error/convert.c/ConvertImageCommand/1542.

    at ChildProcess.onExit (/Users/MyUser/.nvm/v6.7.0/lib/node_modules/nativescript-media-generator/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) code: 1, signal: null }
Write file error { Error: Command failed: convert: invalid argument for option '-extent': /Users/MyUser/MyApp/app/App_Resources/Android/drawable-xxhdpi/splash.png @ error/convert.c/ConvertImageCommand/1542.

    at ChildProcess.onExit (/Users/MyUser/.nvm/v6.7.0/lib/node_modules/nativescript-media-generator/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) code: 1, signal: null }
Write file error { Error: Command failed: convert: invalid argument for option '-extent': /Users/MyUser/MyApp/app/App_Resources/Android/drawable-xxxhdpi/splash.png @ error/convert.c/ConvertImageCommand/1542.

    at ChildProcess.onExit (/Users/MyUser/.nvm/v6.7.0/lib/node_modules/nativescript-media-generator/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5) code: 1, signal: null }
```

**Comment by hypery2k** [comment]
can you post the following output, please:

```
node --version
npm --version
```

**Comment by davorpeic** [comment]
Hi Martin, sure

```
iMac:nativescript-media-generator DavorPeic$ node --version
v6.7.0
iMac:nativescript-media-generator DavorPeic$ npm --version
3.10.3
```

**Comment by hypery2k** [comment]
did you installed imagemagick?
```
brew install imagemagick
```

**Comment by davorpeic** [comment]
yeah

```
bash-3.2$ brew info imagemagick
imagemagick: stable 7.0.5-0 (bottled), HEAD
Tools and libraries to manipulate images in many formats
https://www.imagemagick.org/
/usr/local/Cellar/imagemagick/7.0.5-0 (1,520 files, 22.5M) *
  Poured from bottle on 2017-03-01 at 20:38:56
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/imagemagick.rb
==> Dependencies
Build: pkg-config ✔
Required: libtool ✔, xz ✔
Recommended: jpeg ✔, libpng ✔, libtiff ✔, freetype ✔
Optional: fontconfig ✘, little-cms ✘, little-cms2 ✘, libwmf ✘, librsvg ✘, liblqr ✘, openexr ✘, ghostscript ✘, webp ✘, openjpeg ✘, fftw ✘, pango ✘
==> Requirements
Optional: x11 ✘, perl >= 5.5 ✔```

**Comment by hypery2k** [comment]
could you try the @next version?

**Comment by sugendran** [comment]
Had the same problem, the @next version fixes it.

**Comment by sugendran** [comment]
Of course that adds an extra problem:

```
➜  Tipple git:(master) ✗ tns-media-gen init
module.js:472
    throw err;
    ^

Error: Cannot find module '/Users/sugendran/code/tipple/Tipple/mediagen-config'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/nativescript-media-generator/screenshots.js:9:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by h5gs** [comment]
Try putting node before the command

node tns-media-gen filename fff
