### ISSUE TITLE
Error: Cannot find module 'mediagen-config'

### ISSUE THREAD

**Issue by Ferhatos** [hypery2k/nativescript-media-generator#37]
## What did you do?
`brew install imagemagick`
`npm install -g nativescript-media-generator`
`tns-media-gen app/App_Resources/icons/home.png`

## What did you expect to happen?

success image generation

## What happened instead?

ERROR :
`module.js:549
    throw err;
    ^

Error: Cannot find module '/Users/doulkifle/workespaces/Mihnaty/DispoClick_Mobile/mediagen-config'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/doulkifle/.nvm/versions/node/v8.11.1/lib/node_modules/nativescript-media-generator/screenshots.js:9:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)`
## Your Environment

**NativeScript version:**
"nativescript-angular": "~5.2.0"
**NodeJS and NPM version:**
5.6.0
**Platform(s) running:**
macOs sierra

**Comment by Calinou** [comment]
Try creating a `mediagen-config.json` file with the contents described [here](https://github.com/hypery2k/nativescript-media-generator#example-mediagen-configjson) then try again. You could also run `tns-media-gen init` afterwards to overwrite it (it seems the default options have changed).
